company/urls.py
from django.contrib import admin
from django.urls import path
from company import views

app_name = 'company'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('guidelines/', views.guidelines, name='guidelines'),
]

intern_fair/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import urls as accountUrls
from student import urls as studentUrls
from company import urls as companyUrls
from intern_fair import views
from payments import urls as paymentsUrls
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.home, name="home"),
    path('profile/', views.profile, name="profile"),
    path('admin/', admin.site.urls),
    path('accounts/', include(accountUrls)),
    path('s/', include(studentUrls)),
    path('payments/', include(paymentsUrls)),
    path('c/', include(companyUrls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payments/urls.py
from django.urls import path
from payments import views


app_name = "payments"

urlpatterns = [
    path('payfees/', views.payRegistrationFees, name="pay"),
    path('verify/', views.verifyPayment, name="verify")
]

student/urls.py
from django.contrib import admin
from django.urls import path
from student import views

app_name = 'student'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('guidelines/', views.guidelines, name='guidelines'),
    path('catalog/', views.catalog, name='catalog'),
    path('profilesoffered/', views.getProfilesOffered, name='ProfilesOffered'),
    path('register/<int:id>/', views.register_for_company, name='regcompany'),
    # path('logout/', views.logoutView, name='logout'),
]

student/models.py
from django.db import models
from multiselectfield import MultiSelectField
from django.contrib.auth.models import User
# Create your models here.

# class StudentData(models.Model):
#     CHOICES = (
#         ('w', 'Web Development' ),
#         ('a', 'Coding' ),
#         ('b', 'Analytics' ),
#         ('c', 'Operations' ),
#         ('d', 'Business Development' ),
#         ('d', 'Design' ),
#         ('e', 'Content Development' ),
#         ('f', 'Product Development' ),
#         ('g', 'Finance' ),
#         ('h', 'Sales' ),
#         ('i', 'Management Consulting' ),
#     )
    # cv = models.FileField()
    # role
    # name = models.CharField(max_length=100)
    # entry_number=models.CharField(max_length=200)
    # email = models.EmailField()
    # contact_number = models.IntegerField()
    # college_year=models.IntegerField()

student/views.py
from django.shortcuts import render, reverse
from company import forms
from django.http import HttpResponseRedirect, JsonResponse
from company import models
from accounts import models as accountModels
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.core import serializers
from accounts import forms as accountForms
# Create your views here.

profiles_offered_by_company = [
    {
        'label': "1_option",
        'options': ['Content Development', 'Design', 'Business Development', 'Product Development']
    },
    {
        'label': "2_option",
        'options': ['Web Development', 'Coding', 'Analytics', 'Product Development']
    },
    {
        'label': "3_option",
        'options': ['Web Development', 'Coding', 'Business Development', 'Product Development', 'Design', 'Content Development', 'Others (Drones,Robotics, ROS, Ai/Data Science)']
    },
    {
        'label': "4_option",
        'options': ['Web Development', 'Analytics', 'Product Development', 'Business development', 'Design', 'Finance', 'Sales', 'Management Consulting']
    },
    {
        'label': "5_option",
        'options': ['Business development', 'Design', 'Others (Electronics, Material Science, Mechanical)']
    },
    # {'3_options': ['Content Development', 'Design', 'Business Development', 'Product Development']},
        # ['Content1 Development', 'Design', 'Business Development', 'Product Development'],
]

def getProfilesOffered(request):
    # serialized = serializers.serialize('json', profiles_offered_by_company)
    return JsonResponse(profiles_offered_by_company, safe=False)

def catalog(request):
    flag= False
    context = {}
    if(request.user.is_authenticated):
        queryset = accountModels.StudentProfile.objects.filter(user=request.user)
        message = ""
        if(queryset.count()):
            if(not queryset[0].is_profile_complete):
                message="Please complete your profile and pay your registration fees to apply!"
                flag=False
            else:
                flag=True
        url = request.build_absolute_uri('/s/profilesoffered/')
        posturl = request.build_absolute_uri('/s/register/')
        context = {
            "show_apply" : flag,
            "complete_profile_message": message,
            "fetch_endpoint": url,
            "post_endpoint": posturl,
        }
    
    return render(request, "startup/catalog.html", context)

# http://localhost:8000/s/register/1/?options=2_3
@login_required(login_url="/accounts/signin/")
def register_for_company(request, id):
    queryset = accountModels.StudentProfile.objects.filter(user=request.user)
    if(queryset.count()):
        if(not queryset[0].is_profile_complete):
            return HttpResponseRedirect(reverse("student:profile"))

        try:
            instance = models.RegCompany.objects.get(id=id)
            a = request.GET.get("options")
            if(not a):
                return render(request, "error.html")
            options_index = a.split("_")
            applied_profiles = ""
            for label, option in enumerate(options_index):
                applied_profiles += str(label) + "-" + profiles_offered_by_company[id-1]["options"][int(option)] + "\n"
            student_set = instance.apply_profile.filter(student=queryset[0])
        except Exception:
            return render(request, "error.html")
        if(student_set.count()):
            flag=True
        else:     
            applyProfileInstance = models.ApplyProfile(applied_roles=applied_profiles, student= queryset[0])
            applyProfileInstance.save()
            instance.apply_profile.add(applyProfileInstance)
            instance.save()
            flag=False
        context = {
            'name': queryset[0].name,
            'company_name': instance.name,
            'already_applied': flag
        }
        return render(request, "startup/success.html", context)
    else:
        return render(request, "error.html")


def guidelines(request):
    return render(request, 'student/guidelines.html')

@login_required(login_url="/accounts/signin/")
def profile(request):
    # Checking If the User is already Logged In

    if(request.method=="POST"):
        form = accountForms.UploadCVForm(request.POST, request.FILES)
        if form.is_valid():
            instance = accountModels.StudentProfile.objects.get(user=request.user)
            instance.cv = request.FILES['cv']
            if(instance.reg_fees_paid==True):
                instance.is_profile_complete = True
            instance.save()
            return HttpResponseRedirect(reverse("student:profile"))
    else:
        form = accountForms.UploadCVForm()

        profile = accountModels.Profile.objects.filter(user=request.user)
        if(profile[0].is_student):
            pro = accountModels.StudentProfile.objects.get(user=request.user)
            if(pro.cv):
                uploadedFlag = True
            else:
                uploadedFlag = False
            
            if(pro.is_profile_complete):
                pro_complete = True
            else:
                pro_complete = False
            print(pro_complete)
            data = [
                {"label": "Name", "value": pro.name},
                {"label": "Email", "value": pro.email},
                {"label": "Contact Number", "value": pro.contact_number},
                {"label": "College Year", "value": pro.college_year},
            ]
            context = {
                "data": data,
                "order_status": pro.reg_fees_paid,
                "form": form,
                "uploadedFlag": uploadedFlag,
                "pro_complete": pro_complete
            }
            # print(type(profile[0]))
            # print(dir(profile[0]))
            # for entry in profile[0]:
            #     print(entry)
            return render(request, 'student/display_profile.html', context)
    
    
    # success_msg = ''    
    # mark_flag = False
    # if( request.method == 'POST'):
    #     form = forms.CompanyDataForm(request.POST)
    #     if( form.is_valid() ):
    #         print(form)
    #         formData = models.CompanyData.objects.filter(uid=request.user)
    #         if(formData.count()):
    #             formData[0].address = form.cleaned_data.get('address')
    #             formData[0].your_name = form.cleaned_data.get('your_name')
    #             formData[0].your_postion = form.cleaned_data.get('your_postion')
    #             formData[0].description = form.cleaned_data.get('description')
    #             formData[0].profiles_offered = form.cleaned_data.get('profiles_offered')
    #             formData[0].others = form.cleaned_data.get('others')
    #             formData[0].save()
    #             mark_flag = True
    #             success_msg = "Form Saved Successfully"

    #         else:
    #             instance = form.save(commit=False)
    #             instance.uid = request.user
    #             instance.save()
    #             mark_flag = True
    #             success_msg = "Form Saved Successfully"
    # else:
    #     formData = models.CompanyData.objects.filter(uid=request.user)
    #     if(formData.count()):
    #         print(formData[0])
    #         address = formData[0].address
    #         your_name = formData[0].your_name
    #         your_postion = formData[0].your_postion
    #         description = formData[0].description
    #         profiles_offered = formData[0].profiles_offered
    #         others = formData[0].others
    #         contact_number = formData[0].contact_number
    #         mark_flag = True
    #         form = forms.CompanyDataForm(data={'address': address, 'your_name': your_name, 'your_postion': your_postion, 'description': description, 'profiles_offered':profiles_offered, others:others, 'contact_number': contact_number })
    #     else:
    #         form = forms.CompanyDataForm()
                
    # context = {
    #     'form': form,
    #     'error_msg': message,
    #     'success_msg': success_msg,
    #     'mark_flag': mark_flag
    # }
    # return render(request, 'company/profile.html', context)

templates/student/display_profile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>STUDENT PROFILE || ECELL</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
    <link rel="icon" type="image/png" href="/static/accounts/images/icons/favicon.ico" />
    <link rel="stylesheet" type="text/css" href="/static/accounts/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/static/accounts/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/static/accounts/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
    <link rel="stylesheet" type="text/css" href="/static/accounts/vendor/animate/animate.css">
    <link rel="stylesheet" type="text/css" href="/static/accounts/vendor/css-hamburgers/hamburgers.min.css">
    <link rel="stylesheet" type="text/css" href="/static/accounts/vendor/animsition/css/animsition.min.css">
    <link rel="stylesheet" type="text/css" href="/static/accounts/vendor/select2/select2.min.css">
    <link rel="stylesheet" type="text/css" href="/static/accounts/vendor/daterangepicker/daterangepicker.css">
    <link rel="stylesheet" type="text/css" href="/static/accounts/css/util.css">
    <link rel="stylesheet" type="text/css" href="/static/accounts/css/main.css">
    <link rel="stylesheet" href="/static/base/css/style.css">


</head>
<style>
    #id_profiles_offered {
        /* color: red; */
        /* background-color: blue; */
        border: none;
    }

    textarea {
        /* margin: 100 !important; */
        border: 1px solid grey;
        size: fix;
        resize: none;
        padding: 6px !important;
        /* background-color: blue !important; */
    }

    .field_name {
        font-weight: bold;
    }


    .data-container {
        margin: 10px;
    }

    .data-content {
        border-radius: 10px;
        padding: 15px 10px;
        background-color: lightgrey;
    }
</style>

<body>
    {% include "main/navbar.html" %}
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <div class="login100-form-title" style="background-image: url(/static/accounts/images/bg-01.jpg);">
                    <span class="login100-form-title-1">
                        STUDENT PROFILE
                    </span>
                </div>
                <center>
                    <marquee width="90%" direction="left" height="30px" style="font-weight: bold; font-size: 20px;">
                        Thank you for your response.
                    </marquee>
                </center>

                {% if not order_status %}
                <div class="data-container" data-validate="">
                    <div class="data-content" style="background-color: white; text-align: center; font-size: 17px;">
                        <div style="color: blue; background: #ffbf00; padding: 10px; border-radius: 10px;">
                            <span class="field_name">
                                You Have Not Paid The Fees Yet.
                                <div><a href='{% url "payments:pay" %}' style="color: black; font-size: 18px;">Click
                                        Here</a> to Pay.</div>
                            </span>
                        </div>
                    </div>
                </div>
                {% else %}
                <div class="data-container" data-validate="">
                    <div class="data-content" style="background-color: white; text-align: center; font-size: 17px;">
                        <div style="color: blue; background: #ffbf00; padding: 10px; border-radius: 10px;">
                            <span class="field_name">
                                You Have Successfully Paid The Fees..
                            </span>
                        </div>
                    </div>
                </div>
                {% endif %}
                <tr>
                    <div class="data-container" data-validate="">
                        <div class="data-content"
                            style="color: darkred; font-weight: bold; text-align: center; font-size: 20px; background-color: #c9e915;">
                            <span class="field_name">
                                PROFILE STATUS :
                            </span>
                            <span class="field_data">
                                {% if pro_complete %}
                                    Complete
                                {% else %}
                                    Incomplete
                                {% endif %}

                            </span>
                        </div>
                    </div>
                </tr>
                {% for field in data %}
                <tr>
                    <div class="data-container" data-validate="">
                        <div class="data-content">
                            <span class="field_name">
                                {{ field.label }} :
                            </span>
                            <span class="field_data">
                                {{ field.value }}
                            </span>
                        </div>
                    </div>
                </tr>
                {% endfor %}
                {% if uploadedFlag %}
                <tr>
                    <div class="data-container" data-validate="">
                        <div class="data-content">
                            <span class="field_name">
                                CV :
                            </span>
                            <span class="field_data">
                                Uploaded
                            </span>
                        </div>
                    </div>
                </tr>
                {% else %}
                <form action="/s/profile/" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="data-container">
                        <div class="data-content" style="background: #F57F17">
                            <span class="field_name">
                                {{ form.cv.label }} :
                            </span>
                            <span class="field_data">
                                {{ form.cv }}
                            </span>
                            <span>
                                <button type="submit"
                                    style="background-color: skyblue; padding: 9px; border-radius: 10px; font-weight: bold;">Submit</button>
                            </span>
                        </div>
                    </div>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
    {% include "main/footer.html" %}



    <script src="/static/accounts/vendor/jquery/jquery-3.2.1.min.js"></script>

    <script src="/static/accounts/vendor/animsition/js/animsition.min.js"></script>

    <script src="/static/accounts/vendor/bootstrap/js/popper.js"></script>
    <script src="/static/accounts/vendor/bootstrap/js/bootstrap.min.js"></script>

    <script src="/static/accounts/vendor/select2/select2.min.js"></script>

    <script src="/static/accounts/vendor/daterangepicker/moment.min.js"></script>
    <script src="/static/accounts/vendor/daterangepicker/daterangepicker.js"></script>

    <script src="/static/accounts/vendor/countdowntime/countdowntime.js"></script>

    <script src="/static/accounts/js/main.js"></script>

</body>

</html>

templates/student/guidelines.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Intern Fair </title>
  <link rel="stylesheet" href="/static/base/css/style.css">
  <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="shortcut icon" href="/static/base/images/logo.png">
</head>
<style>
  .link-play-buttons button {
    padding: 15px;
    margin: 10px;
    font-size: 20px;
  }

  .btn-register {
    background: #1c0c35;
    color: #ffffff !important;
    font-weight: bold;
    border: 2px solid #8a57db;
    padding: 20px;
    text-transform: uppercase;
    border-radius: 6px;
    display: inline-block;
    transition: all 0.3s ease 0s;
  }

  .btn-register:hover {
    /* color: #1c0c35 !important; */
    background: #8a57db !important;
    font-weight: 700 !important;
    letter-spacing: 3px;
    text-decoration: none;
    background: none;
    -webkit-box-shadow: 0px 5px 40px -10px rgba(0, 0, 0, 0.57);
    -moz-box-shadow: 0px 5px 40px -10px rgba(0, 0, 0, 0.57);
    transition: all 0.3s ease 0s;
  }

  #register-section {
    background-color: #1c0c35;
    height: 45vh;
    scroll-padding-top: 300px;
    text-align: center;
  }

  .heading-register {
    padding-top: 60px !important;
  }

  #register-section .container .row .btn-register {
    margin-bottom: 15px;
  }

  .heading-register {
    color: white;
    padding: 30px;
    font-weight: bold;
    font-size: 35px;
  }

  .btn-guidelines {
    color: white;
    /* border: 1px ; */
  }

  .btn-guidelines:hover {
    color: yellow;
    box-shadow: yellow;
  }

  .wrapper-btns {
    margin: 10px 0;
  }

  @media only screen and (max-width: 780px) {
    #register-section {
      height: 60vh;
    }
  }
</style>

<body>
  {% include "main/navbar.html" %}

  <!--- About Section ------>
  <section id="about">
    <div class="container">
      <h3 class="title text-center"><b>STUDENT GUIDELINES</b></h3>
      <div class="row">
        <div class="col-md-12 about" style="margin-top: 30px;">
          <ul>
            <li>
              Fill the primary details including Name, College Name, 10th Percentage, 12th Percentage,
              Graduation CG/Percentage (most recent) in the online form. Also, upload your updated
              Resume on the same.
            </li>
            <li>E-Cell does not guarantee assured internship.</li>
            <li>You are supposed to provide valid proofs for all the points mentioned in your resume to the
              company afterwards. In case of invalid information, the candidate will be blacklisted from all
              upcoming events conducted by the institute and respective company policy will be applied.</li>
            <li>Shortlisted candidates will be informed about the interview timings and venue through
              telephonic communication.</li>
            <li>Applicants cannot contact the HR or any other employee of the companies presented in the
              summit. All communications to the companies will be directed through E-Cell.</li>
            <li>In case of any dispute, the decision of E-Cell will be deemed final.</li>
          </ul>
        </div>
        <div class="col-md-6">
          <img src="/static/base/svg/undraw_mobile_marketing_iqbr.svg" class="img-fluid" alt="">
        </div>
      </div>
    </div>
  </section>


  {% include "main/footer.html" %}

  <!--- Smooth Scroll js ---------->
  <script type="text/javascript" src="/static/base/js/smooth-scroll.js"></script>
  <script>
    var scroll = new SmoothScroll('a[href*="#"]');
  </script>
</body>

</html>

templates/student/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>STUDENT PROFILE || ECELL</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="icon" type="image/png" href="/static/accounts/images/icons/favicon.ico" />
	<link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="/static/accounts/vendor/bootstrap/css/bootstrap.min.css">

	<link rel="stylesheet" type="text/css" href="/static/accounts/fonts/font-awesome-4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" type="text/css" href="/static/accounts/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">

	<link rel="stylesheet" type="text/css" href="/static/accounts/vendor/animate/animate.css">

	<link rel="stylesheet" type="text/css" href="/static/accounts/vendor/css-hamburgers/hamburgers.min.css">

	<link rel="stylesheet" type="text/css" href="/static/accounts/vendor/animsition/css/animsition.min.css">

	<link rel="stylesheet" type="text/css" href="/static/accounts/vendor/select2/select2.min.css">

	<link rel="stylesheet" type="text/css" href="/static/accounts/vendor/daterangepicker/daterangepicker.css">

	<link rel="stylesheet" type="text/css" href="/static/accounts/css/util.css">
	<link rel="stylesheet" type="text/css" href="/static/accounts/css/main.css">
	<link rel="stylesheet" href="/static/base/css/style.css">


</head>
<style>
	#id_profiles_offered {
		/* color: red; */
		/* background-color: blue; */
		border: none;
	}
</style>

<body>
	{% include "main/navbar.html" %}

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-form-title" style="background-image: url(/static/accounts/images/bg-01.jpg);">
					<span class="login100-form-title-1">
						STUDENT PROFILE
					</span>
				</div>
				{% if mark_flag %}
				<marquee width="90%" direction="left" height="20px">
					You will be contacted by our representative shortly.
				</marquee>
				{% endif %}
				<form class="login100-form validate-form" method="POST" action="/c/profile/">
					{% csrf_token %}
					{% if success_msg %}
					<div class="successMsg">
						<td style="color: green">
							{{success_msg}}
						</td>
					</div>
					{% endif %}
					{% if form.errors or error_msg %}
					<div class="errorMsg">
						<td style="color: red">
							{{error_msg}}
							{% for field in form.visible_fields %}
							{{ field.errors }}
							{% endfor %}
						</td>
					</div>
					{% endif %}

					{% for field in form.visible_fields %}
					<tr>
						<div class="wrap-input100 m-b-26" data-validate="">
							<span class="label-input100">{{ field.label_tag }}</span>
							{{ field }}
							<span class="focus-input100"></span>
						</div>
					</tr>
					{% endfor %}

					<!-- {% for value, text in form.providers.field.choices %}
					<div class="ui slider checkbox">
						<input id="id_providers_{{ forloop.counter0 }}" name="{{ form.providers.name }}" type="checkbox"
							value="{{ value }}" {% if value in checked_providers %} checked="checked" {% endif %}>
						<label>{{ text }}</label>
					</div>
					{% endfor %} -->
					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							SAVE DATA
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>
	{% include "main/footer.html" %}



	<script src="/static/accounts/vendor/jquery/jquery-3.2.1.min.js"></script>

	<script src="/static/accounts/vendor/animsition/js/animsition.min.js"></script>

	<script src="/static/accounts/vendor/bootstrap/js/popper.js"></script>
	<script src="/static/accounts/vendor/bootstrap/js/bootstrap.min.js"></script>

	<script src="/static/accounts/vendor/select2/select2.min.js"></script>

	<script src="/static/accounts/vendor/daterangepicker/moment.min.js"></script>
	<script src="/static/accounts/vendor/daterangepicker/daterangepicker.js"></script>

	<script src="/static/accounts/vendor/countdowntime/countdowntime.js"></script>

	<script src="/static/accounts/js/main.js"></script>

</body>

</html>