accounts/urls.py
from django.contrib import admin
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('c/signup/', views.companySignUpView, name='company_signup'),
    path('s/signup/', views.studentSignUpView, name='student_signup'),
    path('signin/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
]

company/urls.py
from django.contrib import admin
from django.urls import path
from company import views

app_name = 'company'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('guidelines/', views.guidelines, name='guidelines'),
]

intern_fair/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import urls as accountUrls
from student import urls as studentUrls
from company import urls as companyUrls
from intern_fair import views
from payments import urls as paymentsUrls
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.home, name="home"),
    path('profile/', views.profile, name="profile"),
    path('admin/', admin.site.urls),
    path('accounts/', include(accountUrls)),
    path('s/', include(studentUrls)),
    path('payments/', include(paymentsUrls)),
    path('c/', include(companyUrls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.contrib import admin
from django.urls import path
from student import views

app_name = 'student'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('guidelines/', views.guidelines, name='guidelines'),
    path('catalog/', views.catalog, name='catalog'),
    path('profilesoffered/', views.getProfilesOffered, name='ProfilesOffered'),
    path('register/<int:id>/', views.register_for_company, name='regcompany'),
    # path('logout/', views.logoutView, name='logout'),
]

templates/base/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Intern Fair </title>
  <link rel="stylesheet" href="/static/base/css/style.css">
  <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="shortcut icon" href="/static/base/images/logo.png">
</head>
<style>
  .link-play-buttons button {
    padding: 15px;
    margin: 10px;
    font-size: 20px;
  }

  .btn-register {
    background: #1c0c35;
    color: #ffffff !important;
    font-weight: bold;
    border: 2px solid #8a57db;
    padding: 20px;
    text-transform: uppercase;
    border-radius: 6px;
    display: inline-block;
    transition: all 0.3s ease 0s;
  }

  .btn-register:hover {
    /* color: #1c0c35 !important; */
    background: #8a57db !important;
    font-weight: 700 !important;
    letter-spacing: 3px;
    text-decoration: none;
    background: none;
    -webkit-box-shadow: 0px 5px 40px -10px rgba(0, 0, 0, 0.57);
    -moz-box-shadow: 0px 5px 40px -10px rgba(0, 0, 0, 0.57);
    transition: all 0.3s ease 0s;
  }

  #register-section {
    background-color: #1c0c35;
    height: 45vh;
    scroll-padding-top: 300px;
    text-align: center;
  }

  .heading-register {
    padding-top: 60px !important;
  }

  #register-section .container .row .btn-register {
    margin-bottom: 15px;
  }

  .heading-register {
    color: white;
    padding: 30px;
    font-weight: bold;
    font-size: 35px;
  }
  .btn-guidelines{
    color: white;
    /* border: 1px ; */
  }

  .btn-guidelines:hover{
    color: yellow;
    box-shadow: yellow;
  }
  .wrapper-btns{
    margin: 10px 0;
  }
  @media only screen and (max-width: 780px){
    #register-section{
      height: 60vh;
    }
  }
</style>

<body>
  {% include "main/navbarHome.html" %}
  <!--- Banner Hero section ------->
  <section class="banner">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <p class="promo-title">IIT Ropar Intern Fair</p>
          {% if not user.is_authenticated %}

          <a href="#register-section" class="btn-register"
            style="background-color: transparent; font-size: 25px;">REGISTER</a>
          {% endif %}

        </div>
        <div class="col-md-6" >
          <img src="/static/base/svg/undraw_email_campaign_qa8y.svg" alt="" class="img-fluid">
        </div>
      </div>
    </div>
    <!--- Background wave Hero ---->
    <img src="/static/base/images/ground@-min.png" class="bottom-img" alt="" id="register">
  </section>

  <section id="register-section">
    <div class="heading-register">
      REGISTER AS
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-12 wrapper-btns">
          <div class="row">
            <div class="col-md-12">
              <a href="{% url 'accounts:company_signup' %}" class="btn-register">COMPANY</a>
            </div>
            <div class="col-md-12">
              <a href="{% url 'company:guidelines' %}" class="btn-guidelines">COMPANY GUIDELINES</a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-sm-12 wrapper-btns">
          <div class="row">
            <div class="col-sm-12">
              <a href="{% url 'accounts:student_signup' %}" class="btn-register">STUDENT</a>
            </div>
            <div class="col-md-12">
              <a href="{% url 'student:guidelines' %}" class="btn-guidelines">STUDENT GUIDELINES</a>
            </div>
          </div>
        </div>


      </div>
    </div>
  </section>
  <!--- About Section ------>
  <section id="about">
    <div class="container">
      <h3 class="title text-center">ABOUT US</h3>
      <div class="row">
        <div class="col-md-12 about">
          <p style="margin-top: 30px;">
            Finding the right talent as well as finding the best internship is difficult and tedious for both companies
            and applicants. Inter Fair, IIT Ropar brings a very innovative solution to this problem. It provides a
            platform for companies to hire India’s best talent for different profiles as well as a platform for students
            to get an internship or a placement in these companies.
          </p>
          <h3 class="about-title" style="margin-top: 15px;">Register as company</h3>
          <ul>
            <li>If your organization is looking for access to first-year undergraduates, sophomores and penultimate year
              students from IIT Ropar seeking spring weeks internships then this fair is a great opportunity for early
              engagement and to raise your profile with our highly-motivated students. We want to connect IIT Ropar's
              bright and talented students with employers who are seeking to fill vacancies for jobs or internships in
              their establishment. This is a wonderful opportunity for you to meet students from across all academic
              disciplines and class years, and establish a positive presence on our campus.</li>
            <li>Intern Fair Registration for startups. After you fill the form, one of our team members will contact
              you.</li>
            <li>Please Note: Filling the form is not a confirmation of your participation. Our team will contact you to
              discuss the same.</li>
          </ul>
          <div class="about-title" style="margin-top: 15px;">Register as student</div>
          <ul>
            <li>Internships are a fantastic way to gain some hands-on work experience. Having good grades is of utmost
              importance, but landing on an internship is probably more important to get the most out of it. Learning
              soft
              skills such as communication, will greatly expand your network of influential people. Speaking of
              networks,
              having a group of influential people around will help you greatly in your future. It’s no longer just
              about
              the grades; it's also about your reputation as a hard worker, your ability to sweet-talk an interviewer,
              and
              your desire to improve yourself. At this fair you can explore the opportunities open to you and take your
              first step on the career ladder.</li>
            <li>Companies offering internships and a little info about them -> Registration link for each company ->
              Guidelines -> Registration Form
            </li>
            <li>Please Note: Filling the form is not a confirmation of your participation. Our team will contact you to
              discuss the same.</li>
          </ul>
        </div>

      </div>
      <div class="col-md-6">
        <img src="/static/base/svg/undraw_mobile_marketing_iqbr.svg" class="img-fluid" alt="">
      </div>
    </div>
    </div>
  </section>


  {% include "main/footerHome.html" %}

  <!--- Smooth Scroll js ---------->
  <script type="text/javascript" src="/static/base/js/smooth-scroll.js"></script>
  <script>
    var scroll = new SmoothScroll('a[href*="#"]');
  </script>
</body>

</html>