accounts/urls.py
from django.contrib import admin
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('c/signup/', views.companySignUpView, name='company_signup'),
    path('s/signup/', views.studentSignUpView, name='student_signup'),
    path('signin/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
]

company/urls.py
from django.contrib import admin
from django.urls import path
from company import views

app_name = 'company'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('guidelines/', views.guidelines, name='guidelines'),
]

intern_fair/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import urls as accountUrls
from student import urls as studentUrls
from company import urls as companyUrls
from intern_fair import views
from payments import urls as paymentsUrls
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.home, name="home"),
    path('profile/', views.profile, name="profile"),
    path('admin/', admin.site.urls),
    path('accounts/', include(accountUrls)),
    path('s/', include(studentUrls)),
    path('payments/', include(paymentsUrls)),
    path('c/', include(companyUrls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.contrib import admin
from django.urls import path
from student import views

app_name = 'student'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('guidelines/', views.guidelines, name='guidelines'),
    path('catalog/', views.catalog, name='catalog'),
    path('profilesoffered/', views.getProfilesOffered, name='ProfilesOffered'),
    path('register/<int:id>/', views.register_for_company, name='regcompany'),
    # path('logout/', views.logoutView, name='logout'),
]

templates/main/footer.html
<!-- Footer ------>
<section id="footer">
  <div class="container" style="padding-top: 16px;">
    <div class="row center">
      <div class="col-sm-5 footer-box">
        <img src="/static/base/images/logo.png" alt="">
        <p>
          E-Cell of TBIF (Technology Business Incubation Foundation), IIT ROPAR is a non-profit organisation managed
          by team of students. We help budding entrepreneurs by offering them co-working space, advance computing
          facilities, seed funding, mentorship from experts and other resources required to incubate a company.
        </p>
      </div>
      <div class="col-sm-3 footer-box">
        <p id="contact" style="color: yellow;"><b>CONTACT FOR QUERIES</b></p>
        Vinay Sunda <i class="fa fa-phone"></i>+91-8146672840 </p>
      </div>
      <div class="col-sm-4 footer-box">
        <p id="contact"><b>OUR ADDRESS</b></p>
        <p><i class="fa fa-map-marker"></i>TBIF,3rd floor,Administration Block<br> IIT Ropar, Rupnagar, Punjab-140001</p>
        <p><i class="fa fa-phone"></i>+91-98922 61889</p>
        <p><i class="fa fa-envelope-o"></i>ecell@iitrpr.ac.in</p>
      </div>
      <div class="col-sm-12 ">
        <p class="copyr8" style="color: wheat;">Copyright © 2019. All rights reserved | Ecell IIT Ropar</p>
        <p class="credit" style="font-size: 12px; color: lightgrey;">Credits to Salvatore Mandis for design</p>
      </div>
      <div class="col-sm-12 ">
      </div>
    </div>
    <br>
  </div>
</section>

templates/main/footerHome.html
<!-- Footer ------>
<section id="footer">
  <div class="container">
    <div class="row center">
      <div class="col-sm-4 footer-box">
        <img src="/static/base/images/logo.png" alt="">
        <p>E-Cell of TBIF (Technology Business Incubation Foundation), IIT ROPAR is a non-profit organisation managed
          by team of students. We help budding entrepreneurs by offering them co-working space, advance computing
          facilities, seed funding, mentorship from experts and other resources required to incubate a company.
        </p>
      </div>
      <div class="col-sm-4 footer-box">
        <p id="contact" style="color: yellow;"><b>CONTACT FOR QUERIES</b></p>
        Vinay Sunda <i class="fa fa-phone"></i>+91-8146672840 </p>
      </div>
      <div class="col-sm-4 footer-box">
        <p id="contact"><b>OUR ADDRESS</b></p>
        <p><i class="fa fa-map-marker"></i>TBIF,3rd floor,Administration Block<br> IIT Ropar, Rupnagar, Punjab-140001</p>
        <p><i class="fa fa-phone"></i>+91-98922 61889</p>
        <p><i class="fa fa-envelope-o"></i>ecell@iitrpr.ac.in</p>
      </div>
      <div class="col-sm-12 ">
        <p class="copyr8" style="color: wheat;">Copyright © 2019. All rights reserved | Ecell IIT Ropar</p>
        <p class="credit" style="font-size: 12px; color: lightgrey;">Credits to Salvatore Mandis for design</p>
      </div>
      <div class="col-sm-12 ">
      </div>
    </div>
    <br>
  </div>
</section>

templates/main/navbar.html
<!-- Navbar Menu  ---->
<section id="nav-bar">
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="/">
            <img src="/static/base/images/logo.png" style="height: 12vh;">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'student:catalog' %}">Companies</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href='{% url "accounts:logout" %}'>Logout<span
                            class="sr-only">(current)</span></a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Sign In</a>
                </li>
                <li class="nav-item">

                    <a class="nav-link" href="/#register">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</section>

templates/main/navbarHome.html
<!-- Navbar Menu  ---->
<section id="nav-bar">
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="/">
            <img src="/static/base/images/logo.png" style="height: 12vh;">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'student:catalog' %}">Companies</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href='{% url "accounts:logout" %}'>Logout<span
                            class="sr-only">(current)</span></a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Sign In</a>
                </li>
                <li class="nav-item">

                    <a class="nav-link" href="#register">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</section>